### ISSUE TITLE
  Error 500 SolrCore 'biblio' not available.

### ISSUE THREAD

**Issue by bsesic** [bsesic/tuefind#6]
Error 500 in Solr.
Error message:
```
VuFindSearch\Backend\Exception\RemoteErrorException thrown with message "500 {metadata={error-class=org.apache.solr.common.SolrException,root-error-class=org.apache.solr.core.SolrResourceNotFoundException},msg=SolrCore 'biblio' is not available due to init failure: Could not load conf for core biblio: Error loading solr config from /usr/local/vufind/solr/vufind/biblio/conf/solrconfig.xml,trace=org.apache.solr.common.SolrException: SolrCore 'biblio' is not available due to init failure: Could not load conf for core biblio: Error loading solr config from /usr/local/vufind/solr/vufind/biblio/conf/solrconfig.xml?    at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1151)?    at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:252)?    at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:418)?    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:345)?    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:296)?    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691)?    at org.eclip"

Stacktrace:
#20 VuFindSearch\Backend\Exception\RemoteErrorException in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Backend/Exception/HttpErrorException.php:68
#19 VuFindSearch\Backend\Exception\HttpErrorException:createFromResponse in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php:446
#18 VuFindSearch\Backend\Solr\Connector:send in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php:404
#17 VuFindSearch\Backend\Solr\Connector:trySolrUrls in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php:363
#16 VuFindSearch\Backend\Solr\Connector:query in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php:218
#15 VuFindSearch\Backend\Solr\Connector:search in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Backend.php:115
#14 VuFindSearch\Backend\Solr\Backend:search in /usr/local/vufind/module/VuFindSearch/src/VuFindSearch/Service.php:112
#13 VuFindSearch\Service:search in /usr/local/vufind/module/VuFind/src/VuFind/Search/Solr/Results.php:114
#12 VuFind\Search\Solr\Results:performSearch in /usr/local/vufind/module/VuFind/src/VuFind/Search/Base/Results.php:262
#11 VuFind\Search\Base\Results:performAndProcessSearch in /usr/local/vufind/module/VuFind/src/VuFind/Search/SearchRunner.php:141
#10 VuFind\Search\SearchRunner:run in /usr/local/vufind/module/VuFind/src/VuFind/Controller/AbstractSearch.php:268
#9 VuFind\Controller\AbstractSearch:resultsAction in /usr/local/vufind/module/VuFind/src/VuFind/Controller/SearchController.php:530
#8 VuFind\Controller\SearchController:resultsAction in /usr/local/vufind/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php:82
#7 Zend\Mvc\Controller\AbstractActionController:onDispatch in /usr/local/vufind/vendor/zendframework/zend-eventmanager/src/EventManager.php:322
#6 Zend\EventManager\EventManager:triggerListeners in /usr/local/vufind/vendor/zendframework/zend-eventmanager/src/EventManager.php:179
#5 Zend\EventManager\EventManager:triggerEventUntil in /usr/local/vufind/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php:118
#4 Zend\Mvc\Controller\AbstractController:dispatch in /usr/local/vufind/vendor/zendframework/zend-mvc/src/DispatchListener.php:118
#3 Zend\Mvc\DispatchListener:onDispatch in /usr/local/vufind/vendor/zendframework/zend-eventmanager/src/EventManager.php:322
#2 Zend\EventManager\EventManager:triggerListeners in /usr/local/vufind/vendor/zendframework/zend-eventmanager/src/EventManager.php:179
#1 Zend\EventManager\EventManager:triggerEventUntil in /usr/local/vufind/vendor/zendframework/zend-mvc/src/Application.php:340
#0 Zend\Mvc\Application:run in /usr/local/vufind/public/index.php:85
```

**Comment by mtrojan-ub** [comment]
versuch mal bitte folgendes Skript auszuführen:
/usr/local/vufind/update_tuefind_config.sh

gibts danach immer noch probleme?

wir haben übrigens mittlerweile einen git-hook, vielleicht wäre es für Dich auch sinnvoll diesen zu aktivieren.

/usr/local/vufind/.git/hooks löschen, und ersetzen auf einen Symlink auf
/usr/local/vufind/.git/git-config/hooks

Dann wird bei Dir die solr-Konfiguration automatisch aktualisiert und solr neu gestartet, sobald es beim git pull (bzw. merge) Änderungen gab.

**Comment by bsesic** [comment]
Das Skript hat den Fehler behoben. Den Symlink habe ich auch gesetzt. Ich markiere den Fehler als behoben.
